require 'yaml'
require 'fileutils'

fastlane_version "2.48.0"

default_platform :ios

PROJECT_NAME = ENV['PROJECT_NAME']
KEYSTORE_PASS = ENV['KEYSTORE_PASSWORD']
KEYSTORE_ALIAS = ENV['KEYSTORE_ALIAS']

platform :ios do

  lane :beta do
    get_certificates
    get_provisioning_profile  
    build_app(
      scheme: PROJECT_NAME, 
      workspace:"./#{PROJECT_NAME}/platforms/ios/#{PROJECT_NAME}.xcworkspace"
    )
    upload_to_testflight
    
    #slack(message: "Successfully distributed a new beta build")
  end

end

platform :android do

  lane :beta do
    gradle(
      task: 'assemble', 
      build_type: 'Release', 
      project_dir: "#{PROJECT_NAME}/platforms/android",
      gradle_path: "../../../deploy/gradlew",
      print_command: false,
      properties: {
        "android.injected.signing.store.file" => "deploy/#{PROJECT_NAME}.keystore",
        "android.injected.signing.store.password" => KEYSTORE_PASS,
        "android.injected.signing.key.alias" => KEYSTORE_ALIAS,
        "android.injected.signing.key.password" => KEYSTORE_PASS,
      }
    )
    
    upload_to_play_store(track: 'internal')
    #slack(message: 'Successfully distributed a new beta build')
  end

end
